services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edudroid
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/edudroid?schema=public
      JWT_SECRET: supersecret
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  frontend:
    build:
      context: .
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000/api
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data: {}
