version: '3.9'
services:
  frontend:
    build: ../frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    volumes:
      - ../frontend:/app
  backend:
    build: ../backend
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/feverducation
      - OLLAMA_API_URL=http://ollama:11434
    depends_on:
      - db
      - ollama
    volumes:
      - ../backend:/app
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: feverducation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  ollama:
    image: ollama/ollama:latest
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODEL=llama3.2
      - OLLAMA_CONFIG=/ollama/ollama.config.json
    command: ["serve"]
    networks:
      - default
volumes:
  postgres_data:
  ollama_data:
